### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by PwrSrg** [bkdotcom/PHPDebugConsole#21]
I am trying to get this working on my Drupal server, but keep getting the following error:

`Fatal error: Class 'bdk\Debug\Utilities' not found in bdk/Debug/Debug.php on line 1699`

**Comment by bkdotcom** [comment]
Sorry.
That's embarrassing.

Fixed in v2.3.1
https://github.com/bkdotcom/PHPDebugConsole/releases/tag/v2.3.1

Thanks for giving it a try!

----

If you're willing to be a guinea-pig,  v3.0 is very stable.. just no official release yet.
can be downloaded via
https://github.com/bkdotcom/PHPDebugConsole/archive/master.zip

or, if you were using composer:  
`composer require bdk/debug:dev-master --update-no-dev`

**Comment by PwrSrg** [comment]
I tried 3.0, but get a very similar error:
`Fatal error: Class 'bdk\Debug\Config' not found in bdk/Debug/Debug.php on line 1912`

**Comment by bkdotcom** [comment]
*sigh*
yes... pretty much the same issue...
I thought non-composer autoloading was working in the 3.0 branch..  guess I was wrong.

Fixed!
I've also added a unit-test to ensure it doesn't break going forward

Thanks for your patience

**Comment by PwrSrg** [comment]
Thanks, I'll give it a shot!
